---
AllCops:
  Exclude:
    - vendor/**/*
    - log/**/*
    - db/schema.rb
    - bin/*
    - node_modules/**/*

Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120

Documentation:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - db/migrate/*

Metrics/AbcSize:
  Exclude:
    - db/migrate/*
